version: 2
jobs:
  build:
    docker:
      - image:  mono:4.4.0.182
    steps:
      - checkout
      - run:
          name: Restore
          - MONO_IOMAP=case xbuild/t: Build/p:Configuration="Debug"/p:Platform="x86" API_QLQTPM.sln