version: 2
jobs:
  build:
    docker:
      - image: win/default 
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
          working_directory: Nhom3QuiTrinh/api/api.csproj

