version: 2.1

jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0

        steps:
      - checkout
 
        - run:
          name: Build
          command: dotnet build 
          working_directory: ./api/api.csproj