version: 2.1

docker:
      - image: microsoft/aspnetcore-build:2.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout  
      
      - run:
          name: "Run Build step"
          command: dotnet restore

      - run:
          name: "Run Build step"
          command: dotnet build
     
