version: 2
jobs:
  build:
    docker:
       - image: microsoft/aspnetcore-build
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build api.csproj
          working_directory: API_QLQTPM.api

