version: 2
jobs:
  build:
    docker:
      - image: jetcipher/circleci-dotnet-core:3.0
    steps:
      - checkout
      - run:
          name: build
          command: dotnet msbuild -p:Configuration=Release