version: 2
jobs:
  build:
    docker:
    -  image: windows-default # Windows machine image
    -  resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Build
          command: dotnet build
          working_directory: Nhom3QuiTrinh/api/api.csproj

