version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "api.csproj" }}
      steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: ./Api
       - run:
          name: Build
          command: dotnet build -c Release
          working_directory: ./api/api.csproj
      - store_artifacts:
          path: ./api/api.csproj
